import argparse
import json
from datetime import datetime
from pathlib import Path

from core.ai.elite_engine import generate_elite_artifacts
from core.ai.elite_pipeline import run_elite_pipeline
from core.ai.elite_runtime import EliteRuntime


def scaffold_demo_workspace(target: Path, prompt: str):
    target.mkdir(parents=True, exist_ok=True)
    (target / "web").mkdir(parents=True, exist_ok=True)
    (target / "docs").mkdir(parents=True, exist_ok=True)
    (target / "notes").mkdir(parents=True, exist_ok=True)
    (target / "scripts").mkdir(parents=True, exist_ok=True)
    (target / "tools").mkdir(parents=True, exist_ok=True)

    (target / "README.md").write_text(
        f"# {target.name}\n\nGenerated by elite_demo.py\n\nPrompt:\n{prompt}\n",
        encoding="utf-8",
    )
    (target / "web" / "index.html").write_text(
        "<!doctype html><html><body><h1>Elite Demo Workspace</h1></body></html>\n",
        encoding="utf-8",
    )

    (target / "scripts" / "run_agent.bat").write_text(
        "@echo off\r\ncd /d %~dp0\\..\r\npy tools\\elite_runtime_runner.py\r\n",
        encoding="utf-8",
    )
    (target / "tools" / "elite_runtime_runner.py").write_text(
        "import json\nfrom datetime import datetime\nfrom pathlib import Path\n"
        "ROOT=Path(__file__).resolve().parents[1]\nELITE=ROOT/'docs'/'elite'\nELITE.mkdir(parents=True, exist_ok=True)\n"
        "report={'generated_at':datetime.now().isoformat(timespec='seconds'),'project':ROOT.name,'status':'ok'}\n"
        "(ELITE/'runtime-report.json').write_text(json.dumps(report, indent=2), encoding='utf-8')\n"
        "print('runtime-report written')\n",
        encoding="utf-8",
    )


def write_files(root: Path, payload: dict):
    for rel, content in payload.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Run elite pipeline demo and produce sample output.")
    parser.add_argument("--output", default="elite_demo_output", help="Output directory path")
    parser.add_argument(
        "--prompt",
        default="Build an elite AI dev workspace with autonomous planning, quality gates, and release readiness.",
        help="Prompt to drive the pipeline",
    )
    parser.add_argument("--mode", default="Elite Agent Run", help="Generation mode")
    args = parser.parse_args()

    root = Path(args.output).resolve()
    scaffold_demo_workspace(root, args.prompt)

    elite = generate_elite_artifacts(
        project_path=root,
        mode=args.mode,
        prompt=args.prompt,
        cloud_provider="Auto",
        cloud_profile="quality_max",
    )
    write_files(root, elite)

    pipeline = run_elite_pipeline(
        project_path=root,
        mode=args.mode,
        prompt=args.prompt,
        cloud_provider="Auto",
        cloud_profile="quality_max",
        openrouter_key="",
        groq_key="",
    )
    write_files(root, pipeline)

    runtime = EliteRuntime(str(root), "", "").run()
    summary = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "workspace": str(root),
        "files_written": len(list(root.rglob("*"))),
        "runtime_doctor_score": runtime["final"]["doctor_score"],
        "runtime_report": runtime["final"]["report_path"],
    }
    (root / "docs" / "sample-output.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
